name: set-tag-and-switch-traffic
on:
  workflow_dispatch:
    inputs:
        is_switch_traffic:
          type: boolean
          required: false
          description: 'switch traffic flag'
  push:
    branches:
      - main
      - staging

jobs:
  Deployment:
    permissions:
      contents: 'write'
      id-token: 'write'
    uses: asami-minegishi-visasq/test/.github/workflows/main.yml@feature/test_mine
    with:
      service_name: test
      app_version: v1
