name: pr-env-deploy-on-comment
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]


jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-job"

  Deployment:
    permissions:
      contents: 'write'
      id-token: 'write'
    uses: asami-minegishi-visasq/test/.github/workflows/pr-env-deploy-on-comment.yml@feature/test_mine
    with:
      service_name: test
      app_version: v1
